"use client";

import Link from "next/link";
import { useState, type FormEvent } from "react";
import { catalogReadableError, type CatalogProductView, type CatalogSyncJobView, type CatalogVariantView, type MedusaHealthView } from "./catalog-products-panel";

interface CatalogEventView { readonly id: string; readonly event_type: string; readonly created_at: string; }
async function readJson(response: Response) { return response.json().catch(() => ({ status: "response_unavailable" })) as Promise<Record<string, unknown>>; }
function keyCount(value: unknown) { return value && typeof value === "object" ? Object.keys(value).length : 0; }

export function CatalogProductDetailPanel({ initialProduct, initialVariants, initialSyncJobs, initialEvents, medusaHealth }: { readonly initialProduct: CatalogProductView; readonly initialVariants: readonly CatalogVariantView[]; readonly initialSyncJobs: readonly CatalogSyncJobView[]; readonly initialEvents: readonly CatalogEventView[]; readonly medusaHealth?: MedusaHealthView | null | undefined }) {
  const [product, setProduct] = useState(initialProduct); const [variants, setVariants] = useState(initialVariants); const [syncJobs, setSyncJobs] = useState(initialSyncJobs); const [events, setEvents] = useState(initialEvents); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false); const [rejectReason, setRejectReason] = useState("");
  async function refresh() { const response = await fetch(`/api/catalog/products/${encodeURIComponent(product.productId)}`, { cache: "no-store" }); const payload = await readJson(response); if (response.ok) { setProduct(payload.product as CatalogProductView); setVariants((payload.variants as CatalogVariantView[] | undefined) ?? []); setSyncJobs((payload.syncJobs as CatalogSyncJobView[] | undefined) ?? []); setEvents((payload.events as CatalogEventView[] | undefined) ?? []); } }
  async function action(operation: "submit" | "approve" | "reject" | "archive" | "queue-medusa-sync") { setBusy(true); setError(null); setMessage(null); const response = await fetch(`/api/catalog/products/${encodeURIComponent(product.productId)}/${operation}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(operation === "reject" ? { reason: rejectReason } : {}) }); const payload = await readJson(response); setBusy(false); if (!response.ok) { setError(catalogReadableError(payload, "Ürün işlemi uygulanamadı.")); return; } setRejectReason(""); setMessage(operation === "queue-medusa-sync" ? "Medusa sync işi kuyruğa alındı." : "Ürün durumu güncellendi."); await refresh(); }
  async function createVariant(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); setBusy(true); setError(null); const response = await fetch(`/api/catalog/products/${encodeURIComponent(product.productId)}/variants`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: String(data.get("title") ?? ""), sku: String(data.get("sku") ?? ""), priceAmount: String(data.get("priceAmount") ?? ""), currency: String(data.get("currency") ?? ""), stockQuantity: String(data.get("stockQuantity") ?? "") }) }); const payload = await readJson(response); setBusy(false); if (!response.ok) { setError(catalogReadableError(payload, "Varyant oluşturulamadı.")); return; } form.reset(); setMessage("Varyant kaydı oluşturuldu."); await refresh(); }
  return <div className="catalog-panel">{message ? <p className="form-success">{message}</p> : null}{error ? <p className="form-error">{error}</p> : null}<section className="catalog-health-strip"><div><strong>Medusa katalog köprüsü</strong><span>{medusaHealth?.status === "ok" ? "Hazır, onaylı ürün sync kuyruğuna alınabilir." : "Kısıtlı mod: ürün kayıtları korunuyor."}</span></div><mark data-state={medusaHealth?.status ?? "unknown"}>{medusaHealth?.status === "ok" ? "Hazır" : "Kısıtlı mod"}</mark></section>
    <section className="catalog-section"><header><div><h2>{product.title}</h2><p>{product.productId}</p></div><Link href="/catalog/products">Ürünlere dön</Link></header><dl className="catalog-metadata"><div><dt>Durum</dt><dd>{product.status}</dd></div><div><dt>Moderasyon</dt><dd>{product.moderationStatus}</dd></div><div><dt>Sync</dt><dd>{product.syncStatus}</dd></div><div><dt>Fiyat</dt><dd>{product.basePriceAmount ?? "-"} {product.currency}</dd></div><div><dt>Özellik alanı</dt><dd>{keyCount(product.attributes)}</dd></div><div><dt>Medya kaydı</dt><dd>{Array.isArray(product.media) ? product.media.length : 0}</dd></div><div><dt>SEO alanı</dt><dd>{keyCount(product.seo)}</dd></div></dl><div className="catalog-action-row"><button disabled={busy} onClick={() => action("submit")}>İncelemeye gönder</button><button disabled={busy} onClick={() => action("approve")}>Onayla</button><button disabled={busy || medusaHealth?.status !== "ok"} onClick={() => action("queue-medusa-sync")}>Medusa kuyruğuna al</button><button disabled={busy} onClick={() => action("archive")}>Arşivle</button></div><form className="catalog-inline-form" onSubmit={(event) => { event.preventDefault(); void action("reject"); }}><label>Ret notu<textarea required value={rejectReason} onChange={(event) => setRejectReason(event.target.value)} /></label><button disabled={busy}>Notla reddet</button></form></section>
    <div className="catalog-detail-grid"><section className="catalog-section"><header><div><h2>Varyantlar</h2><p>Fiyat ve stok metadata kayıtları</p></div></header><div className="catalog-card-list">{variants.map((variant) => <article className="catalog-record-card" key={variant.variantId}><strong>{variant.title}</strong><span>{variant.sku ?? variant.variantId}</span><small>{variant.priceAmount ?? "-"} {variant.currency ?? product.currency} · Stok: {variant.stockQuantity ?? "-"}</small></article>)}{!variants.length ? <p className="empty-state">Henüz varyant yok.</p> : null}</div><form className="catalog-form" onSubmit={createVariant}><label>Varyant adı<input name="title" required /></label><label>SKU<input name="sku" /></label><div className="catalog-form-grid"><label>Fiyat<input name="priceAmount" /></label><label>Para birimi<input name="currency" defaultValue={product.currency} /></label></div><label>Stok miktarı<input name="stockQuantity" type="number" min="0" /></label><button disabled={busy}>Varyant ekle</button></form></section>
    <section className="catalog-section"><header><div><h2>Sync işleri</h2><p>Medusa worker bekleyen gerçek işler</p></div></header><div className="catalog-card-list">{syncJobs.map((job) => <article className="catalog-record-card" key={job.jobId}><strong>{job.jobId}</strong><small>{job.status} · Deneme: {job.attemptCount}</small></article>)}{!syncJobs.length ? <p className="empty-state">Henüz sync işi yok.</p> : null}</div></section>
    <section className="catalog-section"><header><div><h2>Olay geçmişi</h2><p>Son katalog audit olayları</p></div></header><div className="catalog-card-list">{events.slice(0, 12).map((event) => <article className="catalog-record-card" key={event.id}><strong>{event.event_type}</strong><small>{event.created_at}</small></article>)}{!events.length ? <p className="empty-state">Henüz katalog olayı yok.</p> : null}</div></section></div>
  </div>;
}
