"use client";

import Link from "next/link";
import { useMemo, useState, type FormEvent } from "react";
import { orderLabel, orderReadableError, readOrderJson, type CommerceOrderReturnView } from "./order-operations-panel";

export function OrderReturnsPanel({ initialReturns }: { readonly initialReturns: readonly CommerceOrderReturnView[] }) {
  const [returns, setReturns] = useState(initialReturns); const [filter, setFilter] = useState("all"); const [rejectId, setRejectId] = useState(""); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const filtered = useMemo(() => returns.filter((item) => filter === "all" || item.status === filter), [filter, returns]);
  async function refresh() { const response = await fetch("/api/orders/returns", { cache: "no-store" }); const payload = await readOrderJson(response); if (response.ok) setReturns((payload.returns as CommerceOrderReturnView[] | undefined) ?? []); }
  async function action(returnId: string, operation: "approve" | "reject", rejectionReason = "") { setBusy(true); setMessage(null); setError(null); const response = await fetch(`/api/orders/returns/${encodeURIComponent(returnId)}/${operation}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ reason: rejectionReason }) }); const payload = await readOrderJson(response); setBusy(false); if (!response.ok) { setError(orderReadableError(payload, "İade kararı kaydedilemedi.")); return; } setRejectId(""); setReason(""); setMessage(operation === "approve" ? "İade talebi onaylandı." : "İade talebi neden bilgisiyle reddedildi."); await refresh(); }
  function reject(event: FormEvent<HTMLFormElement>) { event.preventDefault(); void action(rejectId, "reject", reason); }
  return <div className="catalog-panel">{message ? <p className="form-success">{message}</p> : null}{error ? <p className="form-error">{error}</p> : null}<section className="catalog-toolbar"><label>İade durumu<select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">Tümü</option><option value="requested">Talep edildi</option><option value="approved">Onaylandı</option><option value="rejected">Reddedildi</option></select></label></section><section className="catalog-section"><header><div><h2>İade talepleri</h2><p>{filtered.length} gerçek kayıt gösteriliyor.</p></div></header><div className="catalog-card-list">{filtered.map((item) => <article className="catalog-record-card" key={item.returnId}><header><div><h3>{item.returnId}</h3><p>{item.reason}</p></div><mark>{orderLabel(item.status)}</mark></header><div className="catalog-action-row"><Link href={`/orders/${encodeURIComponent(item.orderId)}`}>Siparişi aç</Link><button disabled={busy} onClick={() => action(item.returnId, "approve")}>Onayla</button><button disabled={busy} onClick={() => setRejectId(item.returnId)}>Reddet</button></div></article>)}{!filtered.length ? <p className="empty-state">Henüz iade talebi yok.</p> : null}</div></section>{rejectId ? <section className="catalog-section"><h2>İade talebini reddet</h2><form className="catalog-form" onSubmit={reject}><label>Ret nedeni<textarea required value={reason} onChange={(event) => setReason(event.target.value)} /></label><button disabled={busy}>Nedenle reddet</button></form></section> : null}</div>;
}
