"use client";

import Link from "next/link";
import { useMemo, useState, type FormEvent } from "react";
import { orderLabel, orderReadableError, readOrderJson, type CommerceOrderRefundView } from "./order-operations-panel";

export function OrderRefundsPanel({ initialRefunds }: { readonly initialRefunds: readonly CommerceOrderRefundView[] }) {
  const [refunds, setRefunds] = useState(initialRefunds); const [filter, setFilter] = useState("all"); const [rejectId, setRejectId] = useState(""); const [reason, setReason] = useState(""); const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  const filtered = useMemo(() => refunds.filter((item) => filter === "all" || item.status === filter), [filter, refunds]);
  async function refresh() { const response = await fetch("/api/orders/refunds", { cache: "no-store" }); const payload = await readOrderJson(response); if (response.ok) setRefunds((payload.refunds as CommerceOrderRefundView[] | undefined) ?? []); }
  async function action(refundId: string, operation: "approve" | "reject", rejectionReason = "") { setBusy(true); setMessage(null); setError(null); const response = await fetch(`/api/orders/refunds/${encodeURIComponent(refundId)}/${operation}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ reason: rejectionReason }) }); const payload = await readOrderJson(response); setBusy(false); if (!response.ok) { setError(orderReadableError(payload, "Refund kararı kaydedilemedi.")); return; } setRejectId(""); setReason(""); setMessage(operation === "approve" ? "Refund iç durumu onaylandı. Ödeme transferi yapılmadı." : "Refund talebi neden bilgisiyle reddedildi."); await refresh(); }
  function reject(event: FormEvent<HTMLFormElement>) { event.preventDefault(); void action(rejectId, "reject", reason); }
  return <div className="catalog-panel">{message ? <p className="form-success">{message}</p> : null}{error ? <p className="form-error">{error}</p> : null}<section className="catalog-toolbar"><label>Refund durumu<select value={filter} onChange={(event) => setFilter(event.target.value)}><option value="all">Tümü</option><option value="pending">Bekliyor</option><option value="approved">Onaylandı</option><option value="rejected">Reddedildi</option></select></label></section><section className="catalog-section"><header><div><h2>Refund kayıtları</h2><p>{filtered.length} gerçek kayıt gösteriliyor. Bu yüzey ödeme transferi yapmaz.</p></div></header><div className="catalog-card-list">{filtered.map((item) => <article className="catalog-record-card" key={item.refundId}><header><div><h3>{item.refundId}</h3><p>{item.amount} {item.currency} · {item.reason}</p></div><mark>{orderLabel(item.status)}</mark></header><div className="catalog-action-row"><Link href={`/orders/${encodeURIComponent(item.orderId)}`}>Siparişi aç</Link><button disabled={busy} onClick={() => action(item.refundId, "approve")}>Onayla</button><button disabled={busy} onClick={() => setRejectId(item.refundId)}>Reddet</button></div></article>)}{!filtered.length ? <p className="empty-state">Henüz refund kaydı yok.</p> : null}</div></section>{rejectId ? <section className="catalog-section"><h2>Refund talebini reddet</h2><form className="catalog-form" onSubmit={reject}><label>Ret nedeni<textarea required value={reason} onChange={(event) => setReason(event.target.value)} /></label><button disabled={busy}>Nedenle reddet</button></form></section> : null}</div>;
}
