"use client";

import Link from "next/link";
import { useState, type FormEvent } from "react";
import { orderLabel, orderReadableError, readOrderJson, type CommerceOrderEventView, type CommerceOrderItemView, type CommerceOrderRefundView, type CommerceOrderReturnView, type CommerceOrderSyncJobView, type CommerceOrderView, type OrderMedusaHealthView } from "./order-operations-panel";

function keyCount(value: unknown) { return value && typeof value === "object" ? Object.keys(value).length : 0; }
export function OrderDetailPanel({ initialOrder, initialItems, initialReturns, initialRefunds, initialEvents, initialSyncJobs, medusaHealth }: { readonly initialOrder: CommerceOrderView; readonly initialItems: readonly CommerceOrderItemView[]; readonly initialReturns: readonly CommerceOrderReturnView[]; readonly initialRefunds: readonly CommerceOrderRefundView[]; readonly initialEvents: readonly CommerceOrderEventView[]; readonly initialSyncJobs: readonly CommerceOrderSyncJobView[]; readonly medusaHealth?: OrderMedusaHealthView | null | undefined }) {
  const [order, setOrder] = useState(initialOrder); const [items, setItems] = useState(initialItems); const [returns, setReturns] = useState(initialReturns); const [refunds, setRefunds] = useState(initialRefunds); const [events, setEvents] = useState(initialEvents); const [syncJobs, setSyncJobs] = useState(initialSyncJobs);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState<string | null>(null); const [error, setError] = useState<string | null>(null); const [cancelReason, setCancelReason] = useState("");
  async function refresh() { const response = await fetch(`/api/orders/${encodeURIComponent(order.orderId)}`, { cache: "no-store" }); const payload = await readOrderJson(response); if (response.ok) { setOrder(payload.order as CommerceOrderView); setItems((payload.items as CommerceOrderItemView[] | undefined) ?? []); setReturns((payload.returns as CommerceOrderReturnView[] | undefined) ?? []); setRefunds((payload.refunds as CommerceOrderRefundView[] | undefined) ?? []); setEvents((payload.events as CommerceOrderEventView[] | undefined) ?? []); setSyncJobs((payload.syncJobs as CommerceOrderSyncJobView[] | undefined) ?? []); } }
  function start() { setBusy(true); setMessage(null); setError(null); }
  async function action(operation: "confirm" | "cancel" | "mark-paid" | "mark-fulfilled" | "queue-medusa-sync") { start(); const response = await fetch(`/api/orders/${encodeURIComponent(order.orderId)}/${operation}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(operation === "cancel" ? { reason: cancelReason } : {}) }); const payload = await readOrderJson(response); setBusy(false); if (!response.ok) { setError(orderReadableError(payload, "Sipariş işlemi uygulanamadı.")); return; } setCancelReason(""); setMessage(operation === "mark-paid" ? "İç ödeme durumu güncellendi; tahsilat yapılmadı." : operation === "queue-medusa-sync" ? "Medusa order sync işi kuyruğa alındı." : "Sipariş durumu güncellendi."); await refresh(); }
  async function createItem(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); start(); const response = await fetch(`/api/orders/${encodeURIComponent(order.orderId)}/items`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: String(data.get("title") ?? ""), productId: String(data.get("productId") ?? ""), variantId: String(data.get("variantId") ?? ""), sellerId: String(data.get("sellerId") ?? ""), sku: String(data.get("sku") ?? ""), quantity: Number(data.get("quantity") ?? 1), unitPriceAmount: String(data.get("unitPriceAmount") ?? ""), taxAmount: String(data.get("taxAmount") ?? "0"), discountAmount: String(data.get("discountAmount") ?? "0") }) }); const payload = await readOrderJson(response); setBusy(false); if (!response.ok) { setError(orderReadableError(payload, "Sipariş kalemi oluşturulamadı.")); return; } form.reset(); setMessage("Sipariş kalemi kaydedildi ve toplamlar yeniden hesaplandı."); await refresh(); }
  async function createReturn(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); start(); const response = await fetch(`/api/orders/${encodeURIComponent(order.orderId)}/returns`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ reason: String(data.get("reason") ?? "") }) }); const payload = await readOrderJson(response); setBusy(false); if (!response.ok) { setError(orderReadableError(payload, "İade talebi oluşturulamadı.")); return; } form.reset(); setMessage("İade talebi kaydedildi."); await refresh(); }
  async function createRefund(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const data = new FormData(form); start(); const response = await fetch(`/api/orders/${encodeURIComponent(order.orderId)}/refunds`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ reason: String(data.get("reason") ?? ""), amount: String(data.get("amount") ?? ""), currency: String(data.get("currency") ?? ""), returnId: String(data.get("returnId") ?? "") }) }); const payload = await readOrderJson(response); setBusy(false); if (!response.ok) { setError(orderReadableError(payload, "Refund talebi oluşturulamadı.")); return; } form.reset(); setMessage("Refund talebi kaydedildi. Ödeme transferi yapılmadı."); await refresh(); }
  return <div className="catalog-panel">{message ? <p className="form-success">{message}</p> : null}{error ? <p className="form-error">{error}</p> : null}<section className="catalog-health-strip"><div><strong>Medusa Bridge Provider · opsiyonel order sync</strong><span>Commerce OS sipariş çekirdeği bağımsızdır. {medusaHealth?.status === "ok" ? "Provider hazır; onaylı sipariş sync kuyruğuna alınabilir." : "Kısıtlı mod: sipariş kayıtları korunuyor."}</span></div><mark data-state={medusaHealth?.status ?? "unknown"}>{medusaHealth?.status === "ok" ? "Provider hazır" : "Kısıtlı mod"}</mark></section>
    <section className="catalog-section"><header><div><h2>{order.orderId}</h2><p>{order.customerEmail ?? order.customerId ?? "Müşteri bilgisi bekleniyor"}</p></div><Link href="/orders">Siparişlere dön</Link></header><dl className="catalog-metadata"><div><dt>Durum</dt><dd>{orderLabel(order.status)}</dd></div><div><dt>Ödeme</dt><dd>{orderLabel(order.paymentStatus)}</dd></div><div><dt>Hazırlama</dt><dd>{orderLabel(order.fulfillmentStatus)}</dd></div><div><dt>Risk</dt><dd>{orderLabel(order.riskStatus)}</dd></div><div><dt>Toplam</dt><dd>{order.totalAmount} {order.currency}</dd></div><div><dt>Fatura adres alanı</dt><dd>{keyCount(order.billingAddress)}</dd></div><div><dt>Teslimat adres alanı</dt><dd>{keyCount(order.shippingAddress)}</dd></div></dl><div className="catalog-action-row"><button disabled={busy} onClick={() => action("confirm")}>Onayla</button><button disabled={busy} onClick={() => action("mark-paid")}>Ödendi işaretle</button><button disabled={busy} onClick={() => action("mark-fulfilled")}>Hazırlandı işaretle</button><button disabled={busy || medusaHealth?.status !== "ok"} onClick={() => action("queue-medusa-sync")}>Medusa kuyruğuna al</button></div><form className="catalog-inline-form" onSubmit={(event) => { event.preventDefault(); void action("cancel"); }}><label>İptal nedeni<textarea required value={cancelReason} onChange={(event) => setCancelReason(event.target.value)} /></label><button disabled={busy}>Nedenle iptal et</button></form></section>
    <div className="catalog-detail-grid"><section className="catalog-section"><header><div><h2>Kalemler</h2><p>Ürün ve fiyat metadata kayıtları</p></div></header><div className="catalog-card-list">{items.map((item) => <article className="catalog-record-card" key={item.itemId}><strong>{item.title}</strong><span>{item.sku ?? item.itemId}</span><small>{item.quantity} adet · {item.totalAmount} {order.currency}</small></article>)}{!items.length ? <p className="empty-state">Henüz sipariş kalemi yok.</p> : null}</div><form className="catalog-form" onSubmit={createItem}><label>Kalem başlığı<input name="title" required /></label><label>Ürün kodu<input name="productId" /></label><label>Varyant kodu<input name="variantId" /></label><label>Satıcı kodu<input name="sellerId" /></label><label>SKU<input name="sku" /></label><div className="catalog-form-grid"><label>Adet<input name="quantity" type="number" min="1" defaultValue="1" /></label><label>Birim fiyat<input name="unitPriceAmount" required /></label></div><div className="catalog-form-grid"><label>Vergi<input name="taxAmount" defaultValue="0" /></label><label>İndirim<input name="discountAmount" defaultValue="0" /></label></div><button disabled={busy}>Kalem ekle</button></form></section>
    <section className="catalog-section"><header><div><h2>İadeler</h2><p>Gerçek iade talepleri</p></div><Link href="/orders/returns">Tüm iadeler</Link></header><div className="catalog-card-list">{returns.map((item) => <article className="catalog-record-card" key={item.returnId}><strong>{item.returnId}</strong><span>{orderLabel(item.status)}</span><small>{item.reason}</small></article>)}{!returns.length ? <p className="empty-state">Henüz iade talebi yok.</p> : null}</div><form className="catalog-form" onSubmit={createReturn}><label>İade nedeni<textarea name="reason" required /></label><button disabled={busy}>İade talebi ekle</button></form></section>
    <section className="catalog-section"><header><div><h2>Refundlar</h2><p>İç refund karar kayıtları</p></div><Link href="/orders/refunds">Tüm refundlar</Link></header><div className="catalog-card-list">{refunds.map((item) => <article className="catalog-record-card" key={item.refundId}><strong>{item.refundId}</strong><span>{orderLabel(item.status)}</span><small>{item.amount} {item.currency}</small></article>)}{!refunds.length ? <p className="empty-state">Henüz refund talebi yok.</p> : null}</div><form className="catalog-form" onSubmit={createRefund}><label>Neden<textarea name="reason" required /></label><label>Tutar<input name="amount" required /></label><label>Para birimi<input name="currency" defaultValue={order.currency} required /></label><label>İade kodu<input name="returnId" /></label><button disabled={busy}>Refund talebi ekle</button></form></section></div>
    <div className="catalog-detail-grid"><section className="catalog-section"><header><div><h2>Sync işleri</h2><p>Medusa worker bekleyen işler</p></div></header><div className="catalog-card-list">{syncJobs.map((job) => <article className="catalog-record-card" key={job.jobId}><strong>{job.jobId}</strong><small>{orderLabel(job.status)} · Deneme: {job.attemptCount}</small></article>)}{!syncJobs.length ? <p className="empty-state">Henüz sync işi yok.</p> : null}</div></section><section className="catalog-section"><header><div><h2>Olay geçmişi</h2><p>Son sipariş audit olayları</p></div></header><div className="catalog-card-list">{events.slice(0, 14).map((event) => <article className="catalog-record-card" key={event.id}><strong>{event.event_type}</strong><small>{event.created_at}</small></article>)}{!events.length ? <p className="empty-state">Henüz sipariş olayı yok.</p> : null}</div></section></div>
  </div>;
}
