[options]
admin_passwd = commerce_os_odoo_admin_password
db_host = postgres
db_port = 5432
db_user = commerce_os
db_password = commerce_os_dev_password
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/enterprise-addons,/mnt/custom-addons,/mnt/localization-packs
data_dir = /var/lib/odoo
list_db = False
proxy_mode = True
without_demo = all
server_wide_modules = base,web
workers = 0
max_cron_threads = 1
log_level = info
